var textStates = {
  ALASKA: 'Alaska',
  ALABAMA: 'Ala.',
  ARKANSAS: 'Ark.',
  ARIZONA: 'Ariz.',
  CALIFORNIA: 'Calif.',
  COLORADO: 'Colo.',
  CONNECTICUT: 'Ct.',
  'WASHINGTON, D.C.': 'D.C.',
  'DISTRICT OF COLUMBIA': 'D.C.',
  DELAWARE: 'Del.',
  FLORIDA: 'Fla.',
  GEORGIA: 'Ga.',
  HAWAII: 'Hawaii',
  IOWA: 'Iowa',
  IDAHO: 'Idaho',
  ILLINOIS: 'Ill.',
  INDIANA: 'Ind.',
  KANSAS: 'Kan.',
  KENTUCKY: 'Ky.',
  LOUISIANA: 'La.',
  MASSACHUSETTS: 'Mass.',
  MARYLAND: 'Md.',
  MICHIGAN: 'Mich.',
  MINNESOTA: 'Minn.',
  MISSOURI: 'Mo.',
  MISSISSIPPI: 'Miss.',
  MONTANA: 'Mont.',
  'NORTH CAROLINA': 'N.C.',
  'NORTH DAKOTA': 'N.D.',
  NEBRASKA: 'Neb.',
  'NEW HAMPSHIRE': 'N.H.',
  'NEW JERSEY': 'N.J.',
  'NEW MEXICO': 'N.M.',
  NEVADA: 'Nev.',
  'NEW YORK': 'N.Y.',
  OHIO: 'Ohio',
  OKLAHOMA: 'Okla.',
  OREGON: 'Ore.',
  PENNSYLVANIA: 'Penn.',
  'RHODE ISLAND': 'R.I.',
  'SOUTH CAROLINA': 'S.C.',
  'SOUTH DAKOTA': 'S.D.',
  TENNESSEE: 'Tenn.',
  TEXAS: 'Texas',
  UTAH: 'Utah',
  VIRGINIA: 'Va.',
  VERMONT: 'Vt.',
  WASHINGTON: 'Wash.',
  WISCONSIN: 'Wis.',
  'WEST VIRGINIA': 'W.Va.',
  WYOMING: 'Wyoming',
};

module.exports = {
  text: textStates,
};
